kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: {{ .Values.frontend.applabel }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}